INSERT INTO Cards (title, taxID, orgMessage, organization)
VALUES 
       ('Ahmedabad Vaccine Initiative', '00-000003', "The foundation supports the states goals in the areas of maternal, newborn, and child health, childhood nutrition, family planning, immunization, and disease control, as well as supporting agricultural development, digital financial inclusion, and womens economic empowerment.", 'Gates Foundation'),
       ('Provide Clean Water to Los Angeles', '00-000004', "Water Drop LA is a 100% volunteer-run community organization whose mission is to provide clean water to communities facing water inaccessibility. By distributing 2,000+ gallons of water to Skid Row, Water Drop aims to support existing organizers and to meet the immediate needs of the community.", 'Water Drop LA'),
       ("Help Scarlet through St. Judes Research", '00-000005', "Scarlet was not well, and doctors suspected something serious. They referred Scarlets case to a pediatric childrens hospital in Louisiana. A few hours later, Scarlets parents, received another call. Scarlet had leukemia. Doctors referred Scarlet to St. Jude Childrens Research Hospital.", 'St. Jude Research'),
       ("Wildlife Law Program", '13-6018549', "We utilize the law to ensure the right of all wildlife to live in an ecosystem free from human manipulation, exploitation, or abuse.", 'Friends of Animals'),
       ("Save Jewish lives in Ukraine now", '13-1656634', "Dedicated to serving the needs of Jews throughout the world, particularly where their lives as Jews are threatened or made more difficult.", 'American Jewish Joint Distribution Committees'),
       ("Guide Dog Foundation for the Blind", '11-1687477', "To improve the quality of life for people who are blind, have low vision, or have other disabilities..", 'Guide Dog Foundation for the Blind'),
       ("Feminist Action for Climate Justice in the Pacific and the Caribbean", '77-0155782', "We envision a world where movements have transformed power and privilege for a few into equity and equality for all. Our movement-led approach embodies a new kind of philanthropy that shifts power into the hands of those working at the frontlines of gender justice.", 'Global Fund for Women');
--        ('Nathan Sparks Ball Donation', '00-0000000', 'To me the most important thing is to have children play with balls. As a child I was deprived of balls when I desperatly wantd them. Therefore, I would not like children of this age to suffer the same fate. Please give me money to donate balls.', 'Sparky Boy Foundation'),
--        ('Find the Biggest Bird', '00-0000001', 'I just need to find the biggest bird. As one does. But to do that I need your help. Give me money', 'William Fredrick Johns Initiave'),
--        ('Get Some Help Fundraiser', '00-0000002', 'I mean, some people just need to get some help. Like look at Joe Biden. That man, he needs some help. Lets get these people help. Now give me money to give them help. I will not take any of it. I promise ;)', 'Help Me Foundation'),